// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoKTEGoE36cShl1UgpVPyfnjvYusV-Ab0',
    appId: '1:639309224927:web:9d6fd1de7440669d8a426a',
    messagingSenderId: '639309224927',
    projectId: 'travelapp-afb4d',
    authDomain: 'travelapp-afb4d.firebaseapp.com',
    storageBucket: 'travelapp-afb4d.firebasestorage.app',
    measurementId: 'G-S44JNJC0BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvifomIj2SAccPubSMNiaw4qKk1Z3i3jk',
    appId: '1:639309224927:android:db08116a69a648728a426a',
    messagingSenderId: '639309224927',
    projectId: 'travelapp-afb4d',
    storageBucket: 'travelapp-afb4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANlyOJ4WA9h8Q6oO0MRRONnHG_bBF-O-E',
    appId: '1:639309224927:ios:fbaa57585986a4138a426a',
    messagingSenderId: '639309224927',
    projectId: 'travelapp-afb4d',
    storageBucket: 'travelapp-afb4d.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANlyOJ4WA9h8Q6oO0MRRONnHG_bBF-O-E',
    appId: '1:639309224927:ios:fbaa57585986a4138a426a',
    messagingSenderId: '639309224927',
    projectId: 'travelapp-afb4d',
    storageBucket: 'travelapp-afb4d.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoKTEGoE36cShl1UgpVPyfnjvYusV-Ab0',
    appId: '1:639309224927:web:fb0b11fe51e7eecd8a426a',
    messagingSenderId: '639309224927',
    projectId: 'travelapp-afb4d',
    authDomain: 'travelapp-afb4d.firebaseapp.com',
    storageBucket: 'travelapp-afb4d.firebasestorage.app',
    measurementId: 'G-QRT5T5S4TS',
  );

}